# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90429a936ffe57e30347ad9a813faca8"
name = "bright-pearl-ship-date-updater"
handle = "bright-pearl-ship-date-updater"
application_url = "https://officially-balanced-designed-closer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brightpear.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://officially-balanced-designed-closer.trycloudflare.com/auth/callback",
  "https://officially-balanced-designed-closer.trycloudflare.com/auth/shopify/callback",
  "https://officially-balanced-designed-closer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
